apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmicroservice-deployment
  namespace: default
  labels:
    app: webmicroservicedemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webmicroservicedemo
  template:
    metadata:
      labels:
        app: webmicroservicedemo
    spec:
      containers:
        - name: webmicroservicedemo
          image: bitsshivraj/webmicroservice:1.0
          ports:
            - containerPort: 9009

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webmicroservicedemo-rollout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmicroservicedemo
  strategy:
    blueGreen:
      activeService: webmicroservicedemo-service
      previewService: webmicroservicedemo-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: webmicroservicedemo
    spec:
      containers:
        - name: webmicroservicedemo
          image: bitsshivraj/webmicroservice:1.0
          ports:
            - containerPort: 9009

---
apiVersion: v1
kind: Service
metadata:
  name: webmicroservicedemo-service
  namespace: default
spec:
  selector:
    app: webmicroservicedemo
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009

---
apiVersion: v1
kind: Service
metadata:
  name: webmicroservicedemo-preview-service
  namespace: default
spec:
  selector:
    app: webmicroservicedemo
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009
