apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmicroservice-deployment
  namespace: default
  labels:
    app: webmicroservicedemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webmicroservicedemo
  template:
    metadata:
      labels:
        app: webmicroservicedemo
    spec:
      containers:
      - name: webmicroservicedemo
        image: bitsshivraj/webmicroservice:1.0
        ports:
        - containerPort: 9009

---
apiVersion: v1
kind: Service
metadata:
  name: webmicroservicedemo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 9009
    targetPort: 9009

