apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: bitsshivraj/webmicroservice:1.0 # Replace with your image path
          ports:
            - containerPort: 9009
          env:
            - name: PORT
              value: "9009"

---

apiVersion: v1
kind: Service
metadata:
  name: webservice-service
spec:
  type: NodePort
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009