apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: bitsshivraj/webmicroservice:1.0 # Replace with your image path
          ports:
            - containerPort: 9009
          resources:
            requests:
              memory: "512Mi"  # Modify as needed
              cpu: "500m"      # Modify as needed
            limits:
              memory: "1Gi"    # Modify as needed
              cpu: "1"         # Modify as needed
          env:
            - name: PORT
              value: "9009"

---

apiVersion: v1
kind: Service
metadata:
  name: webservice-service
spec:
  type: NodePort  # Change to LoadBalancer if you want external access in a cloud environment
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009
      nodePort: 30009  # Only needed for NodePort; this will be the port you access the service on from outside